export const USER_LOGIN_REQUEST = 'USER_LOGIN_REQUEST'
export const USER_LOGIN_SUCCESS = 'USER_LOGIN_SUCCESS'
export const USER_LOGIN_FAIL = 'USER_LOGIN_FAIL'
export const USER_LOGOUT = 'USER_LOGOUT'

export const USER_REGISTER_REQUEST = 'USER_REGISTER_REQUEST'
export const USER_REGISTER_SUCCESS = 'USER_REGISTER_SUCCESS'
export const USER_REGISTER_FAIL = 'USER_REGISTER_FAIL'
export const USER_REGISTER_RESET = 'USER_REGISTER_RESET'

export const JOIN_TEAM_REQUEST = 'JOIN_TEAM_REQUEST'
export const JOIN_TEAM_SUCCESS = 'JOIN_TEAM_SUCCESS'
export const JOIN_TEAM_FAIL = 'JOIN_TEAM_FAIL'
export const JOIN_TEAM_RESET = 'JOIN_TEAM_RESET'

export const CREATE_TEAM_REQUEST = 'CREATE_TEAM_REQUEST'
export const CREATE_TEAM_SUCCESS = 'CREATE_TEAM_SUCCESS'
export const CREATE_TEAM_FAIL = 'CREATE_TEAM_FAIL'
export const CREATE_TEAM_RESET = 'CREATE_TEAM_RESET'

export const TEAM_REQUEST = 'TEAM_REQUEST'
export const TEAM_SUCCESS = 'TEAM_SUCCESS'
export const TEAM_FAIL = 'TEAM_FAIL'
export const TEAM_RESET = 'TEAM_RESET'

export const TOAST_ADD = 'TOAST_ADD'
export const TOAST_RESET = 'TOAST_RESET'

